version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgresql
    environment:
      POSTGRES_DB: bd_gas
      POSTGRES_USER: bd_gas
      POSTGRES_PASSWORD: bd_gas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  wildfly:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wildfly
    environment:
      DB_HOST: db
      DB_NAME: bd_gas
      DB_USER: bd_gas
      DB_PASSWORD: bd_gas
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
